title:             Juniper Networks
email:             younos.nazarian@gmail.com
description:       Juniper Networks Article
author:            Younos Nazarian
baseurl:           "/JJ"
url:               "http://younosnazarian.github.io"

# Social Profiles
linkedin_username:  younos
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
